### ISSUE TITLE
SafeConfigParser is deprecated

### ISSUE THREAD

**Issue by 0-wiz-0** [regit/coccigrep#22]
When building coccigrep with Python 3.12 I see:
```
===> Building for coccigrep-1.20
* Building wheel...
/scratch/wip/coccigrep/work/coccigrep-1.20/src/coccigrep.py:120: SyntaxWarning: invalid escape sequence '\.'
  ptype_regexp = re.compile("^[ )]*\.")
/scratch/wip/coccigrep/work/coccigrep-1.20/src/coccigrep.py:413: SyntaxWarning: invalid escape sequence '\.'
  file_filter = re.compile('^[^\.].*\.cocci$')
Traceback (most recent call last):
  File "/scratch/wip/coccigrep/work/coccigrep-1.20/src/coccigrep.py", line 18, in <module>
    from configparser import SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/usr/pkg/lib/python3.12/configparser.py). Did you mean: 'RawConfigParser'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/pkg/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
    main()
  File "/usr/pkg/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/pkg/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 280, in build_wheel
    return _build_backend().build_wheel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/pkg/lib/python3.12/site-packages/setuptools/build_meta.py", line 421, in build_wheel
    return self._build_with_temp_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/pkg/lib/python3.12/site-packages/setuptools/build_meta.py", line 403, in _build_with_temp_dir
    self.run_setup()
  File "/usr/pkg/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/usr/pkg/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
    exec(code, locals())
  File "<string>", line 3, in <module>
  File "/scratch/wip/coccigrep/work/coccigrep-1.20/src/__init__.py", line 2, in <module>
    from .coccigrep import *
  File "/scratch/wip/coccigrep/work/coccigrep-1.20/src/coccigrep.py", line 20, in <module>
    from ConfigParser import SafeConfigParser
ModuleNotFoundError: No module named 'ConfigParser'

ERROR Backend subprocess exited when trying to invoke build_wheel
*** Error code 1

```

**Comment by 0-wiz-0** [comment]
It's listed in the Python 3.12 deprecations:
https://docs.python.org/3/whatsnew/3.12.html
